---

- name: Generate private key for component
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/admin.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generate a certificate signing request with subject information
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/admin.csr"
    privatekey_path: "{{ cert_dir }}/admin.key"
    basic_constraints: "CA:FALSE"
    extended_key_usage:
      - clientAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    common_name: "admin"
    organization_name: "system:masters"
    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    use_common_name_for_san: false
    create_subject_key_identifier: yes

- name: Generate a certificate
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/admin.crt"
    privatekey_path: "{{ cert_dir }}/admin.key"
    csr_path: "{{ cert_dir }}/admin.csr"
    ownca_path: "{{ cert_dir }}/ca.crt"
    ownca_privatekey_path: "{{ cert_dir }}/ca.key"
    provider: ownca

- name: Copy the private key to local certificate directory
  ansible.builtin.fetch:
    src: "{{ cert_dir }}/admin.key"
    dest: "{{ local_cert_dir }}/admin.key"
    flat: true

- name: Copy the self signed certificate to local certificate directory
  ansible.builtin.fetch:
    src: "{{ cert_dir }}/admin.crt"
    dest: "{{ local_cert_dir }}/admin.crt"
    flat: true

