---

- name: Generate ca private key
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/ca.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    backup: yes

- name: Generate ca certificate signing request with subject information
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/ca.csr"
    privatekey_path: "{{ cert_dir }}/ca.key"
    basic_constraints: "CA:TRUE"
    key_usage: 
      - cRLSign
      - keyCertSign
    use_common_name_for_san: false
    country_name: "{{ country_name }}"
    common_name: "CA"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"

- name: Generate a self signed certificate
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/ca.crt"
    privatekey_path: "{{ cert_dir }}/ca.key"
    csr_path: "{{ cert_dir }}/ca.csr"
    provider: selfsigned

- name: Copy the private key to local certificate directory
  ansible.builtin.fetch:
    src: "{{ cert_dir }}/ca.key"
    dest: "{{ local_cert_dir }}/ca.key"
    flat: true

- name: Copy the self signed certificate to local certificate directory
  ansible.builtin.fetch:
    src: "{{ cert_dir }}/ca.crt"
    dest: "{{ local_cert_dir }}/ca.crt"
    flat: true

