---

- name: Is kubectl installed
  ansible.builtin.stat:
    path: "{{ binary_dir }}/kubectl"
  register: kubectl_install_dir

- block:

  - name: Create kubectl directory
    ansible.builtin.file:
      path: "{{ binary_extract_dir }}/kubectl-{{ kubectl_version }}"
      state: directory

  - name: Download kubectl from network
    ansible.builtin.get_url:
      url: https://dl.k8s.io/v{{ kubectl_version }}/bin/linux/amd64/kubectl
      dest: "{{ binary_extract_dir }}/kubectl-{{ kubectl_version }}"
    when:
      - install_mode == 'network'

  - name: Download kubectl from local dir
    ansible.builtin.copy:
      src: "{{ local_binary_dir }}/kubectl"
      dest: "{{ binary_extract_dir }}/kubectl-{{ kubectl_version }}/kubectl"
      mode: u+x
    when:
      - install_mode == 'local'

  - name: Create symlinks to /usr/local/bin
    ansible.builtin.file:
      src: "{{ binary_extract_dir }}/kubectl-{{ kubectl_version }}/kubectl"
      path: "{{ binary_dir }}/kubectl"
      state: link
      mode: u+x

  when:
    - not kubectl_install_dir.stat.exists
