---

- name: Is runc installed
  ansible.builtin.stat:
    path: "{{ binary_extract_dir }}/runc-{{ runc_version }}"
  register: runc_dir

- block:

  - name: Create runc directory
    ansible.builtin.file:
      path: "{{ binary_extract_dir }}/runc-{{ runc_version }}"
      state: directory

  - name: Download runc from network
    ansible.builtin.get_url:
      url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64
      dest: "{{ binary_extract_dir }}/runc-{{ runc_version }}"
    when:
      - install_mode == 'network'

  - name: Download runc from local dir
    ansible.builtin.copy:
      src: "{{ local_binary_dir }}/runc.amd64"
      dest: "{{ binary_extract_dir }}/runc-{{ runc_version }}"
    when:
      - install_mode == 'local'

  - name: Remane runc.amd64 to runc
    ansible.builtin.command: >
      mv {{ binary_extract_dir }}/runc-{{ runc_version }}/runc.amd64 {{ binary_extract_dir }}/runc-{{ runc_version }}/runc

  - name: Create symlinks to /usr/local/bin
    ansible.builtin.file:
      src: "{{ binary_extract_dir }}/runc-{{ runc_version }}/runc"
      path: "{{ binary_dir }}/runc"
      state: link
      mode: u+x

  when:
    - not runc_dir.stat.exists
