---

- name: Is cni-plugins installed
  ansible.builtin.stat:
    path: "{{ cni_plugins_dir }}"
  register: cni_dir

- block:

  - name: Create cni-plugins directory
    ansible.builtin.file:
      path: "{{ cni_plugins_dir }}"
      state: directory
      recurse: yes
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0755
    become: yes

  - name: Extract cni-plugins
    ansible.builtin.unarchive:
      src: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz"
      dest: "{{ cni_plugins_dir }}"
      remote_src: yes
    become: yes

  when:
    - not cni_dir.stat.exists
