---

- name: Copy certificates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ cert_dir }}"
  with_fileglob:
    - "{{ local_cert_dir }}/ca.*"
    - "{{ local_cert_dir }}/kube-proxy.*"
    - "{{ local_cert_dir }}/{{ inventory_hostname }}.*"

#- name: Copy host certificate
#  ansible.builtin.copy:
#    src: "{{ local_cert_dir }}/{{ inventory_hostname }}.{{ item }}"
#    dest: "{{ cert_dir }}/kubelet.{{ item }}"
#  with_items:
#    - "key"
#    - "crt"
