---

- ansible.builtin.include_tasks:
    file: preset.yaml

- ansible.builtin.include_tasks:
    file: setup_hosts.yaml

- ansible.builtin.include_tasks:
    file: install_certificates.yaml

- ansible.builtin.include_tasks:
    file: install_kubectl.yaml

- ansible.builtin.include_tasks:
    file: install_crictl.yaml

- ansible.builtin.include_tasks:
    file: install_cni_plugins.yaml

- ansible.builtin.include_tasks:
    file: install_runc.yaml

- ansible.builtin.include_tasks:
    file: install_kube_proxy.yaml

- ansible.builtin.include_tasks:
    file: install_containerd.yaml

- ansible.builtin.include_tasks:
    file: install_kubelet.yaml

- ansible.builtin.include_tasks:
    file: add_pod_route.yaml
