---

#- name: create sertificate directory
#  ansible.builtin.file:
#    path: "{{ kubeconfig_dir }}"
#    state: directory
#    mode: "0755"

- name: Ganerate config admin (set cluster)
  ansible.builtin.command: >
    kubectl config set-cluster k8s
    --certificate-authority={{ cert_dir }}/ca.crt
    --embed-certs=true
    --server=https://127.0.0.1:6443
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig

- name: Ganerate config admin (set credentials)
  ansible.builtin.command: >
    kubectl config set-credentials admin
    --client-certificate={{ cert_dir }}/admin.crt
    --client-key={{ cert_dir }}/admin.key
    --embed-certs=true
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig

- name: Ganerate config admin (set context)
  ansible.builtin.command: >
    kubectl config set-context default
    --cluster=k8s
    --user=admin
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig

- name: Set default context for admin config
  ansible.builtin.command: >
    kubectl config use-context default
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig


#- name: Ganerate config for services (set cluster)
#  ansible.builtin.command: >
#    kubectl config set-cluster k8s
#    --certificate-authority={{ cert_dir }}/ca.crt
#    --embed-certs=true
#    --server=https://k8s-master.{{ domain_name }}:6443
#    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
#  with_items:
#    - kube-controller-manager
#    - kube-scheduler

#- name: Ganerate config for services (set credentials)
#  ansible.builtin.command: >
#    kubectl config set-credentials system:{{ item }}
#    --client-certificate={{ cert_dir }}/{{ item }}.crt
#    --client-key={{ cert_dir }}/{{ item }}.key
#    --embed-certs=true
#    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
#  with_items:
#    - kube-controller-manager
#    - kube-scheduler

#- name: Ganerate config for services (set context)
#  an#sible.builtin.command: >
#    kubectl config set-context default
#    --cluster=k8s
#    --user=system:{{ item }}
#    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
#  with_items:
#    - kube-controller-manager
#    - kube-scheduler
#
#- name: Set default context for services config
#  ansible.builtin.command: >
#    kubectl config use-context default
#    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
#  with_items:
#    - kube-controller-manager
#    - kube-scheduler
