---

- name: Ganerate config admin (set cluster)
  ansible.builtin.command: >
    kubectl config set-cluster k8s
    --certificate-authority="{{ cert_dir }}/ca.crt"
    --embed-certs=true
    --server=https://127.0.0.1:6443
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig

- name: Ganerate config admin (set credentials)
  ansible.builtin.command: >
    kubectl config set-credentials admin
    --client-certificate={{ cert_dir }}/admin.crt
    --client-key={{ cert_dir }}/admin.key
    --embed-certs=true
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig

- name: Ganerate config admin (set context)
  ansible.builtin.command: >
    kubectl config set-context default
    --cluster=k8s
    --user=admin
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig

- name: Set default context for admin config
  ansible.builtin.command: >
    kubectl config use-context default
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig
