---

- name: Is kubectl installed
  ansible.builtin.stat:
    path: "{{ binary_dir }}/kubectl"
  register: kubectl_install_dir

- block:

  - name: Install kubectl from url
    ansible.builtin.get_url:
      url: https://dl.k8s.io/v{{ kubectl_version }}/bin/linux/amd64/kubectl
      dest: "{{ binary_dir }}/kubectl"
      mode: u+x
      owner: "{{ user }}"
      group: "{{ group }}"
    when:
      - install_mode == 'http'

  - name: Install kubectl from local dir
    ansible.builtin.copy:
      src: "{{ local_binary_dir }}/kubectl"
      dest: "/usr/local/bin/kubectl"
      mode: u+x
      owner: "{{ user }}"
      group: "{{ group }}"
    when:
      - install_mode == 'local'

  when:
    - not kubectl_install_dir.stat.exists
