---

- name: Is kube-apiserver installed
  ansible.builtin.stat:
    path: "{{ binary_extract_dir }}/kube-apiserver-{{ kube_apiserver_version }}"
  register: kube_apiserver_dir

- block:

  - name: Create kube-apiserver directory
    ansible.builtin.file:
      path: "{{ binary_extract_dir }}/kube-apiserver-{{ kube_apiserver_version }}"
      state: directory

  - name: Extract kube-apiserver
    ansible.builtin.get_url:
      url: https://dl.k8s.io/v{{ kube_apiserver_version }}/bin/linux/amd64/kube-apiserver
      dest: "{{ binary_extract_dir }}/kube-apiserver-{{ kube_apiserver_version }}"
      mode: u+x

  - name: Create symlinks to /usr/local/bin
    ansible.builtin.file:
      src: "{{ binary_extract_dir }}/kube-apiserver-{{ kube_apiserver_version }}/kube-apiserver"
      path: "/usr/local/bin/kube-apiserver"
      state: link

  when:
    - not kube_apiserver_dir.stat.exists


- name: Install service kube-apiserver
  ansible.builtin.template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 0644
  notify:
    - reload systemd

- name: Enable and start kube-apiserver
  ansible.builtin.systemd:
    name: kube-apiserver
    state: started
    enabled: yes

- name: Check started service
  ansible.builtin.service:
    name: kube-apiserver
    state: started
  register: kube_apiserver_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kube-apiserver service is not running. Playbook has stoped."
  when: kube_apiserver_service_status.state != 'started'
