---

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ kubernetes_dir }}/kube-scheduler.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generate a certificate signing request with subject information
  community.crypto.openssl_csr:
    path: "{{ kubernetes_dir }}/kube-scheduler.csr"
    privatekey_path: "{{ kubernetes_dir }}/kube-scheduler.key"
    basic_constraints: "CA:FALSE"
    extended_key_usage:
      - clientAuth
      - serverAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    country_name: "{{ country }}"
    common_name: "system:kube-scheduler"
    organization_name: "system:system:kube-scheduler"
    state_or_province_name: "Russia"
    locality_name: "Saint-Petersburg"
    subject_alt_name: "IP:127.0.0.1,DNS:kube-scheduler"
    create_subject_key_identifier: yes

- name: Generate a certificate
  community.crypto.x509_certificate:
    path: "{{ kubernetes_dir }}/kube-scheduler.crt"
    csr_path: "{{ kubernetes_dir }}/kube-scheduler.csr"
    ownca_path: "{{ kubernetes_dir }}/ca.crt"
    ownca_privatekey_path: "{{ kubernetes_dir }}/ca.key"
    provider: ownca

- name: Install kube-scheduler
  ansible.builtin.get_url:
    url: https://dl.k8s.io/v{{ kube_scheduler_version }}/bin/linux/amd64/kube-scheduler
    dest: /usr/local/bin
    mode: u+x
  become: yes

- name: Copy file kube-scheduler config
  ansible.builtin.template:
    src: kube-scheduler.yaml.j2
    dest: "{{ kubernetes_dir }}/kube-scheduler.yaml"
  become: yes

- name: Install service kube-scheduler
  ansible.builtin.template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    mode: 0644
  notify:
    - reload systemd
  become: yes

- name: Enable and start kube-scheduler
  ansible.builtin.systemd:
    name: kube-scheduler
    state: started
    enabled: yes
  become: yes
