---

- name: Is kube-controller_manager installed
  ansible.builtin.stat:
    path: "{{ binary_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}"
  register: kube_controller_manager_dir

- block:

  - name: Create controller-manager directory
    ansible.builtin.file:
      path: "{{ binary_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}"
      state: directory

  - name: Download controller-manager from url
    ansible.builtin.get_url:
      url: https://dl.k8s.io/v{{ kube_controller_manager_version }}/bin/linux/amd64/kube-controller-manager
      dest: "{{ binary_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}"
    when:
      - install_mode == 'network'

  - name: Download etcd from local dir
    ansible.builtin.copy:
      src: "{{ local_binary_dir }}/kube-controller-manager"
      dest: "{{ binary_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}"
    when:
      - install_mode == 'local'

  - name: Create symlinks to /usr/local/bin
    ansible.builtin.file:
      src: "{{ binary_extract_dir }}/kube-controller-manager-{{ kube_controller_manager_version }}/kube-controller-manager"
      path: "{{ binary_dir }}/kube-controller-manager"
      state: link
      mode: a+x

  when:
    - not kube_controller_manager_dir.stat.exists

- name: Ganerate config for services (set cluster)
  ansible.builtin.command: >
    kubectl config set-cluster k8s
    --certificate-authority={{ cert_dir }}/ca.crt
    --embed-certs=true
    --server=https://k8s-master.{{ domain_name }}:6443
    --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.kubeconfig

- name: Ganerate config for services (set credentials)
  ansible.builtin.command: >
    kubectl config set-credentials system:kube-controller-manager
    --client-certificate={{ cert_dir }}/kube-controller-manager.crt
    --client-key={{ cert_dir }}/kube-controller-manager.key
    --embed-certs=true
    --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.kubeconfig

- name: Ganerate config for services (set context)
  ansible.builtin.command: >
    kubectl config set-context default
    --cluster=k8s
    --user=system:kube-controller-manager
    --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.kubeconfig

- name: Set default context for services config
  ansible.builtin.command: >
    kubectl config use-context default
    --kubeconfig={{ kubeconfig_dir }}/kube-controller-manager.kubeconfig

- name: Install service kube-controller-manager
  ansible.builtin.template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    mode: 0644
  notify:
    - reload systemd

- name: Enable and start kube-controller-manager
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: started
    enabled: yes

- name: Check started service
  ansible.builtin.service:
    name: kube-apiserver
    state: started
  register: kube_controller_manager_service_status

- name: Terminate playbook if service is not running
  ansible.builtin.fail:
    msg: "The kube-controller-manager service is not running. Playbook has stoped."
  when: kube_controller_manager_service_status.state != 'started'
