---

#- name: Install kubectl
#  ansible.builtin.get_url:
#    url: https://dl.k8s.io/v{{ kubectl_version }}/bin/linux/amd64/kubectl
#    dest: /usr/local/bin
#    mode: u+x
#  become: yes



- name: Is kubectl installed
  ansible.builtin.stat:
    path: "{{ kubectl_dir }}/kubectl"
  register: kubectl_install_dir

- block:

  - name: Install kubectl from url
    ansible.builtin.get_url:
      url: https://dl.k8s.io/v{{ kubectl_version }}/bin/linux/amd64/kubectl
      dest: "{{ kubectl_dir }}/kubectl"
      mode: u+x
    become: yes

  when:
    - not kubectl_install_dir.stat.exists


