---

- name: create cert directory
  ansible.builtin.file:
    path: "{{ cert_dir }}"
    state: directory

- name: create kubernetes directory
  ansible.builtin.file:
    path: "{{ kubernetes_dir }}"
    state: directory

- name: create kubeconfig directory
  ansible.builtin.file:
    path: "{{ kubeconfig_dir }}"
    state: directory
